---
title: "2018-01-17_Ecdysteroid extraction_Rhagoletis"
author: "Qinwen Xia"
date: "2018-01-17"
output:
  prettydoc::html_pretty:
    theme: architect
    toc: yes
  pdf_document:
    number_sections: yes
    toc: yes
fontsize: 18pt
---

[Back](https://adnguyen.github.io/Hahn_lab_protocols/) to main page

# General info and notes before starting 

# Reagents 

* 100% Methonal
* HPLC water
* 80% Methonal


# Protocol

1. Ecdysteroids will be extracted from whole bodies (pupa)

2. Five frozen pupae will be pooled into an Eppendorf tube with 5 beads, add 500μl 100% methanol, and       then put into bead beater to homogenize for 15sec at maximum speed.

3. After the homogenization, mixture will stand at room temperature for 10min, and vortex once.

4. Centrifuge at 10,000 x g for 10 min.

5. The supernatant (400μl) will be collected and transferred into a new glass tube.  

6. The pallet will be twice reextracted by adding 400μl 100% methanol and supernatants (400μl) resulting    from each extraction will be pooled into the glass tube. 

7. Methanol will be evaporated using nitrogen. 

8. The extracts will be dissolved in 100μL 80% methanol, vortex and preserved at -20oC for further       analysis. 
