---
title: "Informative title for protocol"
author: "Kylie Lennon, Andrew D. Nguyen"
date: "YYYY-MM-DD format"
output:
  prettydoc::html_pretty:
    theme: architect
    toc: yes
  pdf_document:
    number_sections: yes
    toc: yes
fontsize: 18pt
---

# General info and notes before starting 

## natural history
### Origin  
Rhagoletis pomonella, commonly known as the apply maggot fly is native to North America. Primitively, they ate hawthorn (Crataegus) berries. When apples were introduced to North America in the 17th century, Rhagoletis began to use apples as a host. The large size of an apple reduces the ability of parasitoid wasps penetrating the maggots. However, apples ripen earlier in the season, beginning in early summer. 

### Physical Description 

### Emergence Habits 
Beginning in early summer, adult Rhagoletis begin emerging. After about eight to ten days, females use their ovipositor to inject her eggs into the fruit. Once the eggs hatch, the maggots remain in the fruit. They continue to develop until the fruit falls from the tree. 

# Rhagoletis Project Workflow

## Field Collections

### Locations 
### dates 

## Collecting larvae and pupae

### Reagents 

* Petri Dish, Stackable Lid [#FB0875712](https://www.fishersci.com/shop/products/fisherbrand-petri-dishes-clear-lid-raised-ridge-100-x-15mm/fb0875712)
* Vermiculite [#S-15280](https://www.uline.com/Product/Detail/S-15280/Vermiculite/Vermiculite-Grade-1-4-Cu-Ft-Bag)
* [KCL Solution (350g/L)](https://www.thermofisher.com/order/catalog/product/AM9640G)

### Protocol 

#### Prepare tubes for holding fruit with maggots 
1. Put the metal mesh into tubs, and pour the
fruits onto the metal mesh
    * 1-2 layers of fruit 
    * Use paper towels to clean up juices at the bottom of the tubes as the fruit begins to rot. 
2. Label tubes by site and host of fruit. 
3. Once larvae/pupae begin to exit the fruit, remove the metal mesh from the tub. 
4. Pick up the larvae/pupae gently with your fingers or forcepts, and place in a petri dish 
    * less than 100 per petri dish
5. Place the fruit and metal mesh back into the tubes. 
6. Split the larvae/pupae into several other petri dishes containing wet vermiculite. 
    * less than 100 per petri dish
    * To prepare vermiculite, add water until all of it is wet. Water should not be dripping from dish.
7. Label petri dish with: site, race, collection date of larvae/pupae, fridge date, number specimens per dish. 
    * Fridge date is 13 days after collection date. 
8. Seal each petri dish with tape, and place dishes into a container with saturated potassium chloride (KCl) solution to keep the humidity (85%).
    * KCl Solution: 1L water with 350g of KCl
   
## Weighing and Purging 
On days 10 and 14, the mass of each pupae will be taken. Then, each syringe will be purged. During this process, air is circulated through drierite and water with a pH of 4.0, which removes the carbon dioxide present. This allows the amount of carbon dioxide produced by each pupae to be measured 24 later. 

### Reagents 
* Mettler Toledo Analytical Balance [model no. xp6](https://www.mt.com/us/en/home/products/Laboratory_Weighing_Solutions/Analytical/Excellence/XPE_Analytical_Balance.html)
* Air Tight Syringes [#14-817-29](https://www.fishersci.com/shop/products/airtite-all-plastic-norm-ject-syringes-5ml-6ml-luer-lock-sterile-graduations-0-2cc/1481729)
* Three way leur Valve [#450-361](http://www.utahmed.com/oemstopcocks.htm#)
* [Drierite](https://secure.drierite.com/catalog3/page5.cfm?activeMenu=1)

### Protocol 
#### Weighing 
1. 10 days after the collection date, remove pupae from the vermiculite. Place in a clean petri dish. 
    * Used dampened paper towel to clean all vermicute off of the pupae. 
2. Weigh pupae using an analytical balance to the nearest 0.001 mg. 
3. Place each pupae into separate air tight syringes. 
    * Each syringe should have a colored piece of tape and number. 
4. Twist valve onto syringe.  
    * Make sure the knob with denoted with (off) is in the upward postion. This ensures the pupae will not fall out. 
    
5. Record the number, tape color, site, and mass for each pupae. 
Note: Four blanks should be included in each cohort.

#### Purging 

**Setup**  
* A pump is attached to tubes which run through drierite and into an erlenmeyer flask containing H20 with a pH of 4.0. There are two valves that create a continuous flow of air through the setup. Another tube is used to add clean air into the syringes containing the pupae. 

1. Plug in pump. 

2. Turn the two valves 90 degrees so the closed knob, denoted with (off), is in the downward position. 
      * This will allow continuous clean air flow through the drierite and acidic water.
      * Make sure pupae is in a location where it will not be smashed when valve is rotated. 
    
3. Screw the valve to the end of the suction tube. 
4. Rotate the valve 90 degrees counterclockwise. Wait a few seconds for the air to be cleaned. Then, rotate an additional 180 degrees counterclockwise. 
5. Inject 1ml of air into the syringe. 
6. Rotate valve 90 degrees clockwise and unscrew from tube. 
* This process should be repeated for all of the pupae in the cohort. Record the first and last purging times. 
  
      

## Respirometry 
### Background 
### Reagents 
### Protocol

## Treatment 
### Reagents
* 96 Well Clear Flat Bottom Polystyrene not treated Microplates [Costar#3370](https://catalog2.corning.com/LifeSciences/en-US/Shopping/ProductDetails.aspx?productid=3370(Lifesciences))

### Protocol 

# Trikinetics

## background  
Trinkinetics systems measure the circadian rhythms and sleeping patterns of various types of small animals. The animal is placed in a tube where infared beam arrays continuously monitor the animal's movement.  


### Reagents 
* Conical Screw Cap Microcentrifuge Tubes (2ml) [#02-681-344](https://www.fishersci.com/shop/products/fisherbrand-nonsterile-microcentrifuge-tubes-threaded-end-12/p-194198)  
* Locomotor Activity Monitor [LAM25](http://www.trikinetics.com/Downloads/TriKinetics%20Price%20List%208.2017.pdf)
* 


### Protocol
# References 
