---
title: "Hahn lab Protocols"
output:
  prettydoc::html_pretty:
    theme: architect
    toc: yes
  pdf_document:
    number_sections: yes
    toc: yes
fontsize: 18pt
---

Welcome to the Hahn lab protocols page. Here is a master list of lab procedures we use to understand the physiology of insects. Please visit [our lab page](http://entomology.ifas.ufl.edu/hahn/lab/) to find out more about our work. Click [here](https://github.com/adnguyen/Hahn_lab_protocols) for the github repository for this website.  


List of protocols: 

* [Ecdysteroid Extraction](2018-01-08_ecdysteroid_extraction.html)
* [Gene expression experiments](2018-01-09_Chao_gxp_experiments.html)
* [Clancy's RNA Isolation](2018_1_22_CS_RNAIsolation.html)
* [Clancy's protein isolation](2018_1_22_CS_Protein_Isolation.html)
* [Rhagoletis related protocols](2018-01-16_Rhagoletis_protocols.html)
* [European corn borer rearing](European_corn_borer_rearing.html)
* [Thermal Hardiness Assays in D.melanogaster](2018-06-14_HC_Thermal_Hardiness_Assays_in_D_melanogaster.html)
* [Thermocoupler Calibrations](2018-06-15_HC_thermocoupler_calibration.html)
* [Drosophila SOP](2018-06-26_HC_drosophila_SOP.html)
